//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_areacontabilidad
    {
        public ac_areacontabilidad()
        {
            this.sa_subarea = new ObservableListSource<sa_subarea>();
            this.pc_presupuestocab = new ObservableListSource<pc_presupuestocab>();
            this.Tramite = new ObservableListSource<Tramite>();
        }
    
        public int ac_areacontabilidadid { get; set; }
        public string ac_descripcionarea { get; set; }
        public Nullable<int> ac_areamarcasid { get; set; }
        public Nullable<int> ac_unidadnegocioid { get; set; }
    
        public virtual CArea CArea { get; set; }
        public virtual un_unidadnegocio un_unidadnegocio { get; set; }
        public virtual ObservableListSource<sa_subarea> sa_subarea { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab { get; set; }
        public virtual ObservableListSource<Tramite> Tramite { get; set; }
    }
}
