//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ad_autorizaciondocumento
    {
        public int ad_autorizacioncabid { get; set; }
        public int ad_tipodocumentoautid { get; set; }
        public int ad_documentoid { get; set; }
        public int ad_usuarioautorizador { get; set; }
        public int ad_usuarioautorizado { get; set; }
        public string ad_motivo { get; set; }
        public System.DateTime ad_fechadesde { get; set; }
        public System.DateTime ad_fechahasta { get; set; }
        public Nullable<bool> ad_utilizado { get; set; }
    
        public virtual td_tipodocumento td_tipodocumento { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
