//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atencion
    {
        public Atencion()
        {
            this.OrdenTrabajo = new ObservableListSource<OrdenTrabajo>();
            this.op_oposicion = new ObservableListSource<op_oposicion>();
            this.pc_presupuestocab = new ObservableListSource<pc_presupuestocab>();
            this.AtencionXVia = new ObservableListSource<AtencionXVia>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Obs { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public int AreaID { get; set; }
        public Nullable<int> TarjetaID { get; set; }
    
        public virtual ObservableListSource<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual ObservableListSource<op_oposicion> op_oposicion { get; set; }
        public virtual Area Area { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab { get; set; }
        public virtual ObservableListSource<AtencionXVia> AtencionXVia { get; set; }
    }
}
