//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_pp_pagopresupuesto
    {
        public int pp_pagopresupuestoid { get; set; }
        public Nullable<int> pp_presupuestocabid { get; set; }
        public Nullable<int> pp_monedaid { get; set; }
        public Nullable<int> pp_bancoid { get; set; }
        public Nullable<int> pp_cuentaid { get; set; }
        public Nullable<int> pp_formapagoid { get; set; }
        public Nullable<System.DateTime> pp_fechapago { get; set; }
        public string pp_nrocheque { get; set; }
        public Nullable<int> pp_bancochequeid { get; set; }
        public Nullable<int> pp_monedagastoid { get; set; }
        public Nullable<decimal> pp_gastocambiario { get; set; }
        public Nullable<decimal> pp_montopago { get; set; }
        public string pp_referencia { get; set; }
        public Nullable<System.DateTime> pp_fechaboletadeposito { get; set; }
        public string pp_nrorecibo { get; set; }
        public Nullable<System.DateTime> pp_fecharecibo { get; set; }
        public Nullable<bool> pp_anulado { get; set; }
        public Nullable<System.DateTime> pp_fechanotacredito { get; set; }
        public string pp_notacreditonro { get; set; }
        public Nullable<int> pp_pagomultipleid { get; set; }
        public Nullable<int> pp_notacreditopresupid { get; set; }
        public string pp_nroboletadeposito { get; set; }
        public Nullable<int> pp_respcobroextid { get; set; }
        public Nullable<int> pp_reciboid { get; set; }
        public string Audit_User { get; set; }
        public System.DateTime Audit_Fecha { get; set; }
        public string Audit_Operacion { get; set; }
    }
}
