//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_banco
    {
        public ba_banco()
        {
            this.co_continente = new ObservableListSource<co_continente>();
            this.Cliente = new ObservableListSource<Cliente>();
            this.cb_cuentabanco = new ObservableListSource<cb_cuentabanco>();
            this.ps_pagosolicitud = new ObservableListSource<ps_pagosolicitud>();
            this.ps_pagosolicitud1 = new ObservableListSource<ps_pagosolicitud>();
            this.pp_pagopresupuesto = new ObservableListSource<pp_pagopresupuesto>();
            this.pp_pagopresupuesto1 = new ObservableListSource<pp_pagopresupuesto>();
        }
    
        public int ba_bancoid { get; set; }
        public string ba_descripcion { get; set; }
        public Nullable<int> ba_paisid { get; set; }
        public Nullable<int> ba_ciudadid { get; set; }
        public bool ba_mostrar { get; set; }
    
        public virtual CCiudad CCiudad { get; set; }
        public virtual ObservableListSource<co_continente> co_continente { get; set; }
        public virtual ObservableListSource<Cliente> Cliente { get; set; }
        public virtual ObservableListSource<cb_cuentabanco> cb_cuentabanco { get; set; }
        public virtual ObservableListSource<ps_pagosolicitud> ps_pagosolicitud { get; set; }
        public virtual ObservableListSource<ps_pagosolicitud> ps_pagosolicitud1 { get; set; }
        public virtual CPais CPais { get; set; }
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto { get; set; }
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto1 { get; set; }
    }
}
