//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ca_clienteantecedente
    {
        public int ca_clienteantecedentid { get; set; }
        public int ca_clienteid { get; set; }
        public int ca_tipoantecedenteid { get; set; }
        public Nullable<int> ca_tarifarioid { get; set; }
        public string ca_observacion { get; set; }
        public string ca_tipoantecedente { get; set; }
        public Nullable<int> ca_enviadopor { get; set; }
        public Nullable<int> ca_autorizadopor { get; set; }
        public Nullable<System.DateTime> ca_fechaantecedente { get; set; }
        public Nullable<int> ca_cotizacioncabid { get; set; }
        public Nullable<int> ca_tramiteid { get; set; }
        public Nullable<int> ca_actaanio { get; set; }
        public Nullable<int> ca_actanro { get; set; }
        public Nullable<int> ca_registronro { get; set; }
    
        public virtual ta_tipoantecedente ta_tipoantecedente { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual cc_cotizacioncab cc_cotizacioncab { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
