//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAgenteLocal
    {
        public CAgenteLocal()
        {
            this.Expediente = new ObservableListSource<Expediente>();
            this.Marca = new ObservableListSource<Marca>();
            this.Poder = new ObservableListSource<Poder>();
        }
    
        public int idagloc { get; set; }
        public Nullable<int> identidad { get; set; }
        public int idestado { get; set; }
        public int nromatricula { get; set; }
        public string obs { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> GrupoID { get; set; }
        public Nullable<bool> Nuestro { get; set; }
        public string Iniciales { get; set; }
    
        public virtual ObservableListSource<Expediente> Expediente { get; set; }
        public virtual ObservableListSource<Marca> Marca { get; set; }
        public virtual ObservableListSource<Poder> Poder { get; set; }
    }
}
