//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class cb_cuentabanco
    {
        public cb_cuentabanco()
        {
            this.ccm_conclictamoneda = new ObservableListSource<ccm_conclictamoneda>();
            this.cct_cierrecuenta = new ObservableListSource<cct_cierrecuenta>();
            this.mc_movimientoscuenta = new ObservableListSource<mc_movimientoscuenta>();
            this.pp_pagopresupuesto = new ObservableListSource<pp_pagopresupuesto>();
            this.ps_pagosolicitud = new ObservableListSource<ps_pagosolicitud>();
            this.ps_pagosolicitud1 = new ObservableListSource<ps_pagosolicitud>();
        }
    
        public int cb_cuentabancoid { get; set; }
        public int cb_bancoid { get; set; }
        public string cb_nrocuenta { get; set; }
        public int cb_monedaid { get; set; }
        public string cb_descripcion { get; set; }
        public decimal cb_saldo { get; set; }
        public bool cb_escuentapago { get; set; }
        public string cb_sello { get; set; }
        public string cb_color { get; set; }
    
        public virtual ba_banco ba_banco { get; set; }
        public virtual ObservableListSource<ccm_conclictamoneda> ccm_conclictamoneda { get; set; }
        public virtual ObservableListSource<cct_cierrecuenta> cct_cierrecuenta { get; set; }
        public virtual ObservableListSource<mc_movimientoscuenta> mc_movimientoscuenta { get; set; }
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto { get; set; }
        public virtual ObservableListSource<ps_pagosolicitud> ps_pagosolicitud { get; set; }
        public virtual ObservableListSource<ps_pagosolicitud> ps_pagosolicitud1 { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
