//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCiudad
    {
        public CCiudad()
        {
            this.ba_banco = new ObservableListSource<ba_banco>();
            this.pr_proveedor = new ObservableListSource<pr_proveedor>();
        }
    
        public int idciudad { get; set; }
        public string nombreve { get; set; }
        public string nomciudad { get; set; }
        public Nullable<int> codciudad { get; set; }
        public int idpais { get; set; }
    
        public virtual ObservableListSource<ba_banco> ba_banco { get; set; }
        public virtual ObservableListSource<pr_proveedor> pr_proveedor { get; set; }
        public virtual CPais CPais { get; set; }
    }
}
