//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccm_conclictamoneda
    {
        public int ccm_conclictamonedaid { get; set; }
        public string ccm_tiporelacion { get; set; }
        public int ccm_monedaid { get; set; }
        public int ccm_concliid { get; set; }
        public int ccm_cuentabancoid { get; set; }
    
        public virtual ccm_conclictamoneda ccm_conclictamoneda1 { get; set; }
        public virtual ccm_conclictamoneda ccm_conclictamoneda2 { get; set; }
        public virtual cb_cuentabanco cb_cuentabanco { get; set; }
    }
}
