//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class cct_cierrecuenta
    {
        public int cct_cierrecuentaid { get; set; }
        public int cct_cuentabancoid { get; set; }
        public int cct_cierremovimientoid { get; set; }
        public decimal cct_saldo { get; set; }
    
        public virtual cm_cierremovimiento cm_cierremovimiento { get; set; }
        public virtual cb_cuentabanco cb_cuentabanco { get; set; }
    }
}
