//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ch_clientehistorico
    {
        public int ch_clientehistoricoid { get; set; }
        public int ch_clientenuevoid { get; set; }
        public int ch_clientedataflexid { get; set; }
        public string ch_tarifashistoricas { get; set; }
    }
}
