//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIdioma
    {
        public CIdioma()
        {
            this.DocumentoPlantilla = new ObservableListSource<DocumentoPlantilla>();
            this.Propietario = new ObservableListSource<Propietario>();
            this.Mes = new ObservableListSource<Mes>();
            this.pr_proveedor = new ObservableListSource<pr_proveedor>();
        }
    
        public int ididioma { get; set; }
        public string descrip { get; set; }
        public string abrev { get; set; }
    
        public virtual ObservableListSource<DocumentoPlantilla> DocumentoPlantilla { get; set; }
        public virtual ObservableListSource<Propietario> Propietario { get; set; }
        public virtual ObservableListSource<Mes> Mes { get; set; }
        public virtual ObservableListSource<pr_proveedor> pr_proveedor { get; set; }
    }
}
