//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public Clase()
        {
            this.Marca = new ObservableListSource<Marca>();
        }
    
        public int ID { get; set; }
        public int Nro { get; set; }
        public int NizaEdicionID { get; set; }
        public int ClaseTipoID { get; set; }
        public string Descrip { get; set; }
        public string DescripBreve { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
    
        public virtual ObservableListSource<Marca> Marca { get; set; }
        public virtual ClaseTipo ClaseTipo { get; set; }
    }
}
