//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Atencion = new ObservableListSource<Atencion>();
            this.ca_clienteantecedente = new ObservableListSource<ca_clienteantecedente>();
            this.ClienteXTramite = new ObservableListSource<ClienteXTramite>();
            this.ClienteXTramite1 = new ObservableListSource<ClienteXTramite>();
            this.Expediente = new ObservableListSource<Expediente>();
            this.Marca = new ObservableListSource<Marca>();
            this.ncp_notacreditopresup = new ObservableListSource<ncp_notacreditopresup>();
            this.op_oposicion = new ObservableListSource<op_oposicion>();
            this.OrdenTrabajo = new ObservableListSource<OrdenTrabajo>();
            this.pmu_pagomultiple = new ObservableListSource<pmu_pagomultiple>();
            this.tc_tarifascliente = new ObservableListSource<tc_tarifascliente>();
            this.rc_reclamocliente = new ObservableListSource<rc_reclamocliente>();
            this.pc_presupuestocab = new ObservableListSource<pc_presupuestocab>();
            this.spc_solicitudpagocab = new ObservableListSource<spc_solicitudpagocab>();
            this.ps_pagosolicitud = new ObservableListSource<ps_pagosolicitud>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Documento { get; set; }
        public string RUC { get; set; }
        public string Personeria { get; set; }
        public string Obs { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdiomaID { get; set; }
        public Nullable<int> PaisID { get; set; }
        public bool Multiple { get; set; }
        public Nullable<int> GrupoEmpresarialID { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> TraduccionAuto { get; set; }
        public Nullable<int> CiudadID { get; set; }
        public Nullable<bool> Inubicable { get; set; }
        public Nullable<int> Ddi { get; set; }
        public Nullable<bool> PGeneral { get; set; }
        public Nullable<bool> PIntelectual { get; set; }
        public Nullable<bool> Distribuidor { get; set; }
        public Nullable<bool> FacturaLocal { get; set; }
        public Nullable<int> TipoSistElectronicoID { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
        public Nullable<int> BancoID { get; set; }
    
        public virtual ObservableListSource<Atencion> Atencion { get; set; }
        public virtual ba_banco ba_banco { get; set; }
        public virtual ObservableListSource<ca_clienteantecedente> ca_clienteantecedente { get; set; }
        public virtual ObservableListSource<ClienteXTramite> ClienteXTramite { get; set; }
        public virtual ObservableListSource<ClienteXTramite> ClienteXTramite1 { get; set; }
        public virtual ObservableListSource<Expediente> Expediente { get; set; }
        public virtual ObservableListSource<Marca> Marca { get; set; }
        public virtual ObservableListSource<ncp_notacreditopresup> ncp_notacreditopresup { get; set; }
        public virtual ObservableListSource<op_oposicion> op_oposicion { get; set; }
        public virtual ObservableListSource<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual ObservableListSource<pmu_pagomultiple> pmu_pagomultiple { get; set; }
        public virtual ObservableListSource<tc_tarifascliente> tc_tarifascliente { get; set; }
        public virtual ObservableListSource<rc_reclamocliente> rc_reclamocliente { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab { get; set; }
        public virtual ObservableListSource<spc_solicitudpagocab> spc_solicitudpagocab { get; set; }
        public virtual ObservableListSource<ps_pagosolicitud> ps_pagosolicitud { get; set; }
        public virtual cr_clienteretencion cr_clienteretencion { get; set; }
    }
}
