//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class cm_cierremovimiento
    {
        public cm_cierremovimiento()
        {
            this.cct_cierrecuenta = new ObservableListSource<cct_cierrecuenta>();
        }
    
        public int cm_cierremovid { get; set; }
        public int cm_mescierre { get; set; }
        public int cm_anhocierre { get; set; }
        public System.DateTime cm_fechacierre { get; set; }
    
        public virtual ObservableListSource<cct_cierrecuenta> cct_cierrecuenta { get; set; }
    }
}
