//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_continente
    {
        public co_continente()
        {
            this.CPais = new ObservableListSource<CPais>();
        }
    
        public int co_continenteid { get; set; }
        public string co_descripcion { get; set; }
        public Nullable<int> co_bancoid { get; set; }
    
        public virtual ba_banco ba_banco { get; set; }
        public virtual ObservableListSource<CPais> CPais { get; set; }
    }
}
