//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigPresup
    {
        public int ID { get; set; }
        public Nullable<int> Anio { get; set; }
        public string Serie { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<bool> Vigente { get; set; }
    }
}
