//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class cp_cotizacionesxpresup
    {
        public int cp_cotipresupid { get; set; }
        public int cp_presupuestocabid { get; set; }
        public int cp_cotizacionid { get; set; }
    
        public virtual cc_cotizacioncab cc_cotizacioncab { get; set; }
        public virtual pc_presupuestocab pc_presupuestocab { get; set; }
    }
}
