//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class cr_clienteretencion
    {
        public int cr_clienteretencionid { get; set; }
        public int cr_clienteid { get; set; }
        public int cr_porcentajeiva10 { get; set; }
        public int cr_porcentajerenta { get; set; }
        public long cr_nrotimbrado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
