//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxm_cobranzasxmov
    {
        public int cxm_cobranzaxmovid { get; set; }
        public int cxm_cobranzaid { get; set; }
        public int cxm_movimientoid { get; set; }
    
        public virtual mc_movimientoscuenta mc_movimientoscuenta { get; set; }
        public virtual pp_pagopresupuesto pp_pagopresupuesto { get; set; }
    }
}
