//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    
    public partial class DatosFacturaNC
    {
        public int FacturaCabId { get; set; }
        public string NroFactura { get; set; }
        public string NroTimbrado { get; set; }
        public string AbrevMoneda { get; set; }
        public string ClienteNombre { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public decimal MontoFactura { get; set; }
        public Nullable<bool> EsDE { get; set; }
    }
}
