//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoPlantilla
    {
        public int ID { get; set; }
        public string Clave { get; set; }
        public int IdiomaID { get; set; }
        public Nullable<int> TramiteID { get; set; }
        public string PlantillaHTML { get; set; }
        public Nullable<int> DocumentoTipoID { get; set; }
        public string Descrip { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> Plural { get; set; }
        public Nullable<int> MergeID { get; set; }
        public Nullable<bool> EnTramite { get; set; }
    
        public virtual CIdioma CIdioma { get; set; }
        public virtual Tramite Tramite { get; set; }
    }
}
