//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class dr_depositorecaudacion
    {
        public int dr_depositorecaudacionid { get; set; }
        public int dr_reciboid { get; set; }
        public System.DateTime dr_fechadeposito { get; set; }
        public int dr_cuentadepositoid { get; set; }
        public string dr_nroboleta { get; set; }
        public int dr_monedaid { get; set; }
        public decimal dr_monto { get; set; }
        public int dr_usuariocargaid { get; set; }
    
        public virtual cb_cuentabanco cb_cuentabanco { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual re_recibo re_recibo { get; set; }
    }
}
