//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    
    public partial class FacturasParaRecibos
    {
        public int FacturaCabId { get; set; }
        public Nullable<int> TimbradoId { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public string NroFactura { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string ClienteNombre { get; set; }
        public string TipoFacturaDescrip { get; set; }
        public string RUC { get; set; }
        public Nullable<bool> EsDocumentoElectronico { get; set; }
        public int MonedaId { get; set; }
        public string MonedaAbrev { get; set; }
        public decimal TotalExentas { get; set; }
        public decimal TotalIVA5 { get; set; }
        public decimal TotalIVA10 { get; set; }
        public decimal LiqIVA5 { get; set; }
        public decimal LiqIVA10 { get; set; }
        public decimal TotalIVA { get; set; }
        public decimal Total { get; set; }
        public string DocumentosAsociados { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> ImporteCobrado { get; set; }
        public string CDC { get; set; }
        public string TipoDocumento { get; set; }
        public string EstadoDE { get; set; }
        public int IdParaOrden { get; set; }
        public Nullable<int> FacturaCabIdRel { get; set; }
        public string MonedaDescrip { get; set; }
        public Nullable<int> FacturaPresupuestoCabId { get; set; }
    }
}
