//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class fp_formadepago
    {
        public fp_formadepago()
        {
            this.pmu_pagomultiple = new ObservableListSource<pmu_pagomultiple>();
            this.pp_pagopresupuesto = new ObservableListSource<pp_pagopresupuesto>();
            this.ps_pagosolicitud = new ObservableListSource<ps_pagosolicitud>();
        }
    
        public int fp_formadepagoid { get; set; }
        public string fp_descripcion { get; set; }
    
        public virtual ObservableListSource<pmu_pagomultiple> pmu_pagomultiple { get; set; }
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto { get; set; }
        public virtual ObservableListSource<ps_pagosolicitud> ps_pagosolicitud { get; set; }
    }
}
