//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class fpc_facturapresupuestocab
    {
        public fpc_facturapresupuestocab()
        {
            this.fpd_facturapresupuestodet = new ObservableListSource<fpd_facturapresupuestodet>();
        }
    
        public int fpc_facturapresupuestocabid { get; set; }
        public int fpc_facturacabid { get; set; }
        public bool fpc_activo { get; set; }
    
        public virtual ObservableListSource<fpd_facturapresupuestodet> fpd_facturapresupuestodet { get; set; }
        public virtual fc_facturacabecera fc_facturacabecera { get; set; }
    }
}
