//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class fpd_facturapresupuestodet
    {
        public int fpd_facturapresupuestodetid { get; set; }
        public int fpd_facturapresupuestocabid { get; set; }
        public int fpd_presupuestocabid { get; set; }
    
        public virtual fpc_facturapresupuestocab fpc_facturapresupuestocab { get; set; }
        public virtual pc_presupuestocab pc_presupuestocab { get; set; }
    }
}
