//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    
    public partial class GetMergeAviVencEspeciales_Result1
    {
        public Nullable<int> ClienteID { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Multiple { get; set; }
        public string Correo { get; set; }
        public Nullable<int> IdiomaID { get; set; }
        public string Idioma { get; set; }
        public string Denominacion { get; set; }
        public Nullable<int> MarcaTipoID { get; set; }
        public Nullable<int> ClaseID { get; set; }
        public Nullable<int> ExpedienteID { get; set; }
        public Nullable<int> RegistroNro { get; set; }
        public Nullable<int> RegistroAnio { get; set; }
        public Nullable<System.DateTime> VencimientoFecha { get; set; }
        public Nullable<int> Marca_ClienteID { get; set; }
        public Nullable<int> Expe_ClienteID { get; set; }
        public Nullable<int> PropietarioID { get; set; }
        public string PNombre { get; set; }
        public string PDireccion { get; set; }
        public Nullable<int> MarcaID { get; set; }
        public Nullable<int> TipoAtencionxMarca { get; set; }
        public Nullable<int> IDTipoAtencionxMarca { get; set; }
    }
}
