//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class gg_gastogeneral
    {
        public gg_gastogeneral()
        {
            this.spc_solicitudpagocab = new ObservableListSource<spc_solicitudpagocab>();
        }
    
        public int gg_gastogeneralid { get; set; }
        public string gg_descripcion { get; set; }
    
        public virtual ObservableListSource<spc_solicitudpagocab> spc_solicitudpagocab { get; set; }
    }
}
