//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    
    public partial class ListaSolArchivo
    {
        public long SolPagoArchCabId { get; set; }
        public int SolPagoArchCabProveedorId { get; set; }
        public int SolPagoArchCabTipoFacturaId { get; set; }
        public string SolPagoArchCabNroFactura { get; set; }
        public System.DateTime SolPagoArchCabFechaFactura { get; set; }
        public decimal SolPagoArchCabMontoTotal { get; set; }
        public bool SolPagoArchCabActivo { get; set; }
        public int SolPagoArchDetSolPagoDetId { get; set; }
        public decimal SolPagoArchDetCantidadIVA10 { get; set; }
        public decimal SolPagoArchDetPrecioUnitarioIVA10 { get; set; }
        public decimal SolPagoArchDetSolPagoDetTotal { get; set; }
        public Nullable<bool> TienAutorizacionVigente { get; set; }
        public string SolPagoArchCabTipoFacturaDescrip { get; set; }
        public string SolPagoArchCabProveedorNombre { get; set; }
        public int SolPagoArchCabMonedaId { get; set; }
        public string SolPagoArchCabMonedaAbrev { get; set; }
        public int SolPagoArchCabSolPagoCabId { get; set; }
        public Nullable<int> SolPagoArchCabClienteId { get; set; }
        public string SolPagoArchCabClienteNombre { get; set; }
    }
}
