//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcaRegRen
    {
        public MarcaRegRen()
        {
            this.Marca = new ObservableListSource<Marca>();
            this.Expediente = new ObservableListSource<Expediente>();
        }
    
        public int ID { get; set; }
        public int ExpedienteID { get; set; }
        public Nullable<int> RegistroNro { get; set; }
        public Nullable<int> RegistroAnio { get; set; }
        public Nullable<System.DateTime> ConcesionFecha { get; set; }
        public Nullable<bool> Limitada { get; set; }
        public Nullable<bool> Vigente { get; set; }
        public string RefMarca { get; set; }
        public string ObsAvRen { get; set; }
        public Nullable<bool> TituloError { get; set; }
        public string Registro { get; set; }
        public Nullable<System.DateTime> VencimientoFecha { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
    
        public virtual ObservableListSource<Marca> Marca { get; set; }
        public virtual ObservableListSource<Expediente> Expediente { get; set; }
        public virtual Expediente Expediente1 { get; set; }
    }
}
