//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class mc_movimientoscuenta
    {
        public mc_movimientoscuenta()
        {
            this.cxm_cobranzasxmov = new ObservableListSource<cxm_cobranzasxmov>();
        }
    
        public int mc_movimientoid { get; set; }
        public int mc_cuentabancoid { get; set; }
        public System.DateTime mc_fechamovimiento { get; set; }
        public int mc_tipomovimientoid { get; set; }
        public decimal mc_montomovimiento { get; set; }
        public string mc_observacion { get; set; }
        public string mc_estado { get; set; }
        public Nullable<System.DateTime> mc_fechaanulacion { get; set; }
        public Nullable<int> mc_pagosolicitudid { get; set; }
        public string mc_nroboleta { get; set; }
        public Nullable<System.DateTime> mc_fechaboleta { get; set; }
        public Nullable<bool> mc_asociadocobranza { get; set; }
    
        public virtual tm_tipomovimientocuenta tm_tipomovimientocuenta { get; set; }
        public virtual ObservableListSource<cxm_cobranzasxmov> cxm_cobranzasxmov { get; set; }
        public virtual cb_cuentabanco cb_cuentabanco { get; set; }
        public virtual ps_pagosolicitud ps_pagosolicitud { get; set; }
    }
}
