//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class me_motivoemision
    {
        public me_motivoemision()
        {
            this.nc_notacreditocabecera = new ObservableListSource<nc_notacreditocabecera>();
        }
    
        public int me_motivoemisionid { get; set; }
        public int me_motivoemisionsifenid { get; set; }
        public string me_motivoemisionsifendescrip { get; set; }
        public bool me_mostrar { get; set; }
    
        public virtual ObservableListSource<nc_notacreditocabecera> nc_notacreditocabecera { get; set; }
    }
}
