//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class MergeDoc
    {
        public MergeDoc()
        {
            this.Merge_Expediente = new ObservableListSource<Merge_Expediente>();
            this.pc_presupuestocab = new ObservableListSource<pc_presupuestocab>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public byte[] Contenido { get; set; }
        public Nullable<int> FuncionarioID { get; set; }
        public string Url { get; set; }
        public Nullable<int> MergeExpedienteID { get; set; }
        public string Serie { get; set; }
        public Nullable<int> NroPresupuesto { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<int> MergeID { get; set; }
        public string Obs { get; set; }
        public string Extension { get; set; }
    
        public virtual ObservableListSource<Merge_Expediente> Merge_Expediente { get; set; }
        public virtual Merge_Expediente Merge_Expediente1 { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab { get; set; }
    }
}
