//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merge_Expediente
    {
        public Merge_Expediente()
        {
            this.MergeDoc1 = new ObservableListSource<MergeDoc>();
            this.pm_pcabxmergeexpe = new ObservableListSource<pm_pcabxmergeexpe>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ExpedienteID { get; set; }
        public int MergeID { get; set; }
        public Nullable<int> MergeDocID { get; set; }
        public bool Generado { get; set; }
        public bool Terminado { get; set; }
        public Nullable<int> TramiteID { get; set; }
        public Nullable<int> FuncionarioID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> EnTramite { get; set; }
        public Nullable<int> ExpedienteIDPadre { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public byte[] Documento { get; set; }
        public Nullable<int> ExpedienteExtID { get; set; }
        public Nullable<int> TramiteSitID { get; set; }
        public Nullable<int> Aux { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        public virtual Merge Merge { get; set; }
        public virtual MergeDoc MergeDoc { get; set; }
        public virtual op_oposicion op_oposicion { get; set; }
        public virtual Tramite_Sit Tramite_Sit { get; set; }
        public virtual ObservableListSource<MergeDoc> MergeDoc1 { get; set; }
        public virtual ObservableListSource<pm_pcabxmergeexpe> pm_pcabxmergeexpe { get; set; }
    }
}
