//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mes
    {
        public int ID { get; set; }
        public int ididioma { get; set; }
        public short Orden { get; set; }
        public string Mes1 { get; set; }
    
        public virtual CIdioma CIdioma { get; set; }
    }
}
