//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class mn_menu
    {
        public mn_menu()
        {
            this.mn_menu1 = new ObservableListSource<mn_menu>();
            this.rm_rolmenu = new ObservableListSource<rm_rolmenu>();
        }
    
        public int mn_idmenu { get; set; }
        public Nullable<int> mn_sistemaid { get; set; }
        public Nullable<int> mn_idmenupadre { get; set; }
        public string mn_clave { get; set; }
        public string mn_titulo { get; set; }
        public string mn_rutarelativa { get; set; }
        public int mn_nivel { get; set; }
        public Nullable<int> mn_orden { get; set; }
        public string mn_tipo { get; set; }
        public Nullable<bool> mn_activo { get; set; }
        public Nullable<bool> mn_permisosespeciales { get; set; }
    
        public virtual ObservableListSource<mn_menu> mn_menu1 { get; set; }
        public virtual mn_menu mn_menu2 { get; set; }
        public virtual ObservableListSource<rm_rolmenu> rm_rolmenu { get; set; }
    }
}
