//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public Moneda()
        {
            this.cb_cuentabanco = new ObservableListSource<cb_cuentabanco>();
            this.cc_cotizacioncab = new ObservableListSource<cc_cotizacioncab>();
            this.ncp_notacreditopresup = new ObservableListSource<ncp_notacreditopresup>();
            this.pc_presupuestocab = new ObservableListSource<pc_presupuestocab>();
            this.pc_presupuestocab1 = new ObservableListSource<pc_presupuestocab>();
            this.pmu_pagomultiple = new ObservableListSource<pmu_pagomultiple>();
            this.ps_pagosolicitud = new ObservableListSource<ps_pagosolicitud>();
            this.rc_reclamocliente = new ObservableListSource<rc_reclamocliente>();
            this.rcm_relacotizamone = new ObservableListSource<rcm_relacotizamone>();
            this.rcm_relacotizamone1 = new ObservableListSource<rcm_relacotizamone>();
            this.sec_solexclusioncab = new ObservableListSource<sec_solexclusioncab>();
            this.spc_solicitudpagocab = new ObservableListSource<spc_solicitudpagocab>();
            this.tc_tarifascliente = new ObservableListSource<tc_tarifascliente>();
            this.tcd_tipocambiode = new ObservableListSource<tcd_tipocambiode>();
            this.nc_notacreditocabecera = new ObservableListSource<nc_notacreditocabecera>();
            this.pp_pagopresupuesto = new ObservableListSource<pp_pagopresupuesto>();
            this.pp_pagopresupuesto1 = new ObservableListSource<pp_pagopresupuesto>();
            this.dr_depositorecaudacion = new ObservableListSource<dr_depositorecaudacion>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PaisID { get; set; }
        public string Descripcion { get; set; }
        public string AbrevMoneda { get; set; }
        public string DescripIngles { get; set; }
        public string PatrixMonedaID { get; set; }
        public string MonedaFE { get; set; }
        public string MonedaDescripFE { get; set; }
    
        public virtual ObservableListSource<cb_cuentabanco> cb_cuentabanco { get; set; }
        public virtual ObservableListSource<cc_cotizacioncab> cc_cotizacioncab { get; set; }
        public virtual CPais CPais { get; set; }
        public virtual ObservableListSource<ncp_notacreditopresup> ncp_notacreditopresup { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab1 { get; set; }
        public virtual ObservableListSource<pmu_pagomultiple> pmu_pagomultiple { get; set; }
        public virtual ObservableListSource<ps_pagosolicitud> ps_pagosolicitud { get; set; }
        public virtual ObservableListSource<rc_reclamocliente> rc_reclamocliente { get; set; }
        public virtual ObservableListSource<rcm_relacotizamone> rcm_relacotizamone { get; set; }
        public virtual ObservableListSource<rcm_relacotizamone> rcm_relacotizamone1 { get; set; }
        public virtual ObservableListSource<sec_solexclusioncab> sec_solexclusioncab { get; set; }
        public virtual ObservableListSource<spc_solicitudpagocab> spc_solicitudpagocab { get; set; }
        public virtual ObservableListSource<tc_tarifascliente> tc_tarifascliente { get; set; }
        public virtual ObservableListSource<tcd_tipocambiode> tcd_tipocambiode { get; set; }
        public virtual ObservableListSource<nc_notacreditocabecera> nc_notacreditocabecera { get; set; }
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto { get; set; }
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto1 { get; set; }
        public virtual ObservableListSource<dr_depositorecaudacion> dr_depositorecaudacion { get; set; }
    }
}
