//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class mu_mergeurgparte
    {
        public int mu_mergeurgparteid { get; set; }
        public int mu_situacionid { get; set; }
        public string mu_dirigidoa { get; set; }
        public string mu_urgirdescrip { get; set; }
        public string mu_personadirigida { get; set; }
    
        public virtual mu_mergeurgparte mu_mergeurgparte1 { get; set; }
        public virtual mu_mergeurgparte mu_mergeurgparte2 { get; set; }
        public virtual Situacion Situacion { get; set; }
    }
}
