//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ncp_notacreditopresup
    {
        public ncp_notacreditopresup()
        {
            this.ncd_notacreditopresupdetalle = new ObservableListSource<ncd_notacreditopresupdetalle>();
            this.pp_pagopresupuesto = new ObservableListSource<pp_pagopresupuesto>();
        }
    
        public int ncp_notacreditoid { get; set; }
        public int ncp_nrocomprobante { get; set; }
        public System.DateTime ncp_fecha { get; set; }
        public int ncp_clienteid { get; set; }
        public int ncp_monedaid { get; set; }
        public decimal ncp_monto { get; set; }
        public bool ncp_anulado { get; set; }
        public Nullable<System.DateTime> ncp_fechaanulacion { get; set; }
        public string ncp_referenciacliente { get; set; }
        public string ncp_cuerponota { get; set; }
        public decimal ncp_saldo { get; set; }
        public string ncp_presupuestos { get; set; }
    
        public virtual ObservableListSource<ncd_notacreditopresupdetalle> ncd_notacreditopresupdetalle { get; set; }
        public virtual ncp_notacreditopresup ncp_notacreditopresup1 { get; set; }
        public virtual ncp_notacreditopresup ncp_notacreditopresup2 { get; set; }
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
