//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class nd_notacreditodetalle
    {
        public int nd_notacreditodetalleid { get; set; }
        public int nd_notacreditocabeceraid { get; set; }
        public decimal nd_cantidad { get; set; }
        public string nd_descripcion { get; set; }
        public decimal nd_preciounitario { get; set; }
        public decimal nd_exentas { get; set; }
        public decimal nd_cincoporciento { get; set; }
        public decimal nd_diezporciento { get; set; }
        public int nd_presupuestocabid { get; set; }
        public string nd_nroboletadeposito { get; set; }
        public Nullable<int> nd_cobroid { get; set; }
        public string nd_descripFE { get; set; }
    
        public virtual nc_notacreditocabecera nc_notacreditocabecera { get; set; }
    }
}
