//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class nf_numeracionfactura
    {
        public int nf_numeracionfacturaid { get; set; }
        public int nf_timbradoid { get; set; }
        public long nf_ultnrofactura { get; set; }
    
        public virtual nf_numeracionfactura nf_numeracionfactura1 { get; set; }
        public virtual nf_numeracionfactura nf_numeracionfactura2 { get; set; }
        public virtual ti_timbrado ti_timbrado { get; set; }
    }
}
