//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class pc_presupuestocab
    {
        public pc_presupuestocab()
        {
            this.cp_cotizacionesxpresup = new ObservableListSource<cp_cotizacionesxpresup>();
            this.pd_presupuestodetalle = new ObservableListSource<pd_presupuestodetalle>();
            this.pm_pcabxmergeexpe = new ObservableListSource<pm_pcabxmergeexpe>();
            this.fpd_facturapresupuestodet = new ObservableListSource<fpd_facturapresupuestodet>();
            this.fd_facturadetalle = new ObservableListSource<fd_facturadetalle>();
            this.pp_pagopresupuesto = new ObservableListSource<pp_pagopresupuesto>();
        }
    
        public int pc_presupuestocabid { get; set; }
        public Nullable<int> pc_mergedocid { get; set; }
        public int pc_tramiteid { get; set; }
        public System.DateTime pc_fechageneracion { get; set; }
        public int pc_clienteid { get; set; }
        public Nullable<int> pc_atencionid { get; set; }
        public int pc_monedaid { get; set; }
        public decimal pc_total { get; set; }
        public decimal pc_saldo { get; set; }
        public Nullable<int> pc_areaid { get; set; }
        public int pc_enviadopor { get; set; }
        public int pc_autorizadopor { get; set; }
        public string pc_estado { get; set; }
        public string pc_partenombre { get; set; }
        public string pc_contrapartenombre { get; set; }
        public Nullable<System.DateTime> pc_fechaanulacion { get; set; }
        public string pc_origen { get; set; }
        public string pc_nropresupuesto { get; set; }
        public string pc_string1 { get; set; }
        public Nullable<bool> pc_reemplazado { get; set; }
        public string pc_string2 { get; set; }
        public string pc_descripcion { get; set; }
        public string pc_concepto { get; set; }
        public string pc_timbrado { get; set; }
        public string pc_razonsocialfactura { get; set; }
        public string pc_rucfactura { get; set; }
        public Nullable<System.DateTime> pc_fechadocreemplazado { get; set; }
        public string pc_telefonofactura { get; set; }
        public Nullable<int> pc_reempsolicporid { get; set; }
        public string pc_nrocasopatrix { get; set; }
        public Nullable<int> pc_facturacabid { get; set; }
        public Nullable<int> pc_recargoatmonedaid { get; set; }
        public Nullable<decimal> pc_recargoatmonto { get; set; }
        public string pc_presupcabidsreemplazo { get; set; }
    
        public virtual ac_areacontabilidad ac_areacontabilidad { get; set; }
        public virtual Atencion Atencion { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ObservableListSource<cp_cotizacionesxpresup> cp_cotizacionesxpresup { get; set; }
        public virtual MergeDoc MergeDoc { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ObservableListSource<pd_presupuestodetalle> pd_presupuestodetalle { get; set; }
        public virtual ObservableListSource<pm_pcabxmergeexpe> pm_pcabxmergeexpe { get; set; }
        public virtual pc_presupuestocab pc_presupuestocab1 { get; set; }
        public virtual pc_presupuestocab pc_presupuestocab2 { get; set; }
        public virtual ObservableListSource<fpd_facturapresupuestodet> fpd_facturapresupuestodet { get; set; }
        public virtual Tramite Tramite { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Moneda Moneda1 { get; set; }
        public virtual fc_facturacabecera fc_facturacabecera { get; set; }
        public virtual ObservableListSource<fd_facturadetalle> fd_facturadetalle { get; set; }
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto { get; set; }
    }
}
