//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_presupuestohistorico
    {
        public Nullable<System.DateTime> ph_fechadocumento { get; set; }
        public Nullable<int> ph_nroagente { get; set; }
        public Nullable<int> ph_clienteid { get; set; }
        public string ph_anombrede { get; set; }
        public string ph_agente { get; set; }
        public string ph_objeto { get; set; }
        public string ph_moneda { get; set; }
        public Nullable<decimal> ph_monto { get; set; }
        public string ph_nrodocumento { get; set; }
        public string ph_tramite { get; set; }
        public string ph_responsable { get; set; }
        public Nullable<System.DateTime> ph_fechapago { get; set; }
        public Nullable<decimal> ph_difbancaria { get; set; }
        public string ph_ruc { get; set; }
        public string ph_formapago { get; set; }
        public Nullable<decimal> ph_montopago { get; set; }
        public string ph_bancoabrev { get; set; }
        public string ph_nombrebanco { get; set; }
        public Nullable<System.DateTime> ph_fechaboleta { get; set; }
        public int ph_presupuestohistoricoid { get; set; }
    }
}
