//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_pcabxmergeexpe
    {
        public int pm_pcabmergeexpid { get; set; }
        public int pm_presupuestocabid { get; set; }
        public int pm_mergeexpedienteid { get; set; }
    
        public virtual Merge_Expediente Merge_Expediente { get; set; }
        public virtual pc_presupuestocab pc_presupuestocab { get; set; }
    }
}
