//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poder
    {
        public Poder()
        {
            this.ExpedienteXPoder = new ObservableListSource<ExpedienteXPoder>();
            this.PropietarioXPoder = new ObservableListSource<PropietarioXPoder>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PoderInscID { get; set; }
        public Nullable<int> PoderTipoID { get; set; }
        public Nullable<int> ExpedienteID { get; set; }
        public Nullable<int> PaisID { get; set; }
        public string Concepto { get; set; }
        public string Denominacion { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> InscripcionNro { get; set; }
        public Nullable<int> InscripcionAnio { get; set; }
        public System.DateTime AltaFecha { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int AgenteLocalID { get; set; }
        public bool Nuestra { get; set; }
        public bool LegNot { get; set; }
        public bool LegCons { get; set; }
        public bool LegRelExt { get; set; }
        public string Obs { get; set; }
        public string Inscripcion { get; set; }
        public Nullable<int> ActaNro { get; set; }
        public Nullable<int> ActaAnio { get; set; }
        public Nullable<bool> Original { get; set; }
    
        public virtual Expediente Expediente { get; set; }
        public virtual ObservableListSource<ExpedienteXPoder> ExpedienteXPoder { get; set; }
        public virtual ObservableListSource<PropietarioXPoder> PropietarioXPoder { get; set; }
        public virtual CAgenteLocal CAgenteLocal { get; set; }
    }
}
