//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class pp_pagopresupuesto
    {
        public pp_pagopresupuesto()
        {
            this.cxm_cobranzasxmov = new ObservableListSource<cxm_cobranzasxmov>();
            this.ncd_notacreditopresupdetalle = new ObservableListSource<ncd_notacreditopresupdetalle>();
        }
    
        public int pp_pagopresupuestoid { get; set; }
        public int pp_presupuestocabid { get; set; }
        public int pp_monedaid { get; set; }
        public Nullable<int> pp_bancoid { get; set; }
        public Nullable<int> pp_cuentaid { get; set; }
        public Nullable<int> pp_formapagoid { get; set; }
        public System.DateTime pp_fechapago { get; set; }
        public string pp_nrocheque { get; set; }
        public Nullable<int> pp_bancochequeid { get; set; }
        public Nullable<int> pp_monedagastoid { get; set; }
        public Nullable<decimal> pp_gastocambiario { get; set; }
        public decimal pp_montopago { get; set; }
        public string pp_referencia { get; set; }
        public Nullable<System.DateTime> pp_fechaboletadeposito { get; set; }
        public string pp_nrorecibo { get; set; }
        public Nullable<System.DateTime> pp_fecharecibo { get; set; }
        public bool pp_anulado { get; set; }
        public Nullable<System.DateTime> pp_fechanotacredito { get; set; }
        public string pp_notacreditonro { get; set; }
        public Nullable<int> pp_pagomultipleid { get; set; }
        public Nullable<int> pp_notacreditopresupid { get; set; }
        public string pp_nroboletadeposito { get; set; }
        public Nullable<int> pp_respcobroextid { get; set; }
        public Nullable<int> pp_reciboid { get; set; }
    
        public virtual ba_banco ba_banco { get; set; }
        public virtual ba_banco ba_banco1 { get; set; }
        public virtual cb_cuentabanco cb_cuentabanco { get; set; }
        public virtual ObservableListSource<cxm_cobranzasxmov> cxm_cobranzasxmov { get; set; }
        public virtual fp_formadepago fp_formadepago { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Moneda Moneda1 { get; set; }
        public virtual ObservableListSource<ncd_notacreditopresupdetalle> ncd_notacreditopresupdetalle { get; set; }
        public virtual ncp_notacreditopresup ncp_notacreditopresup { get; set; }
        public virtual pc_presupuestocab pc_presupuestocab { get; set; }
        public virtual pmu_pagomultiple pmu_pagomultiple { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual re_recibo re_recibo { get; set; }
    }
}
