//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        public Propietario()
        {
            this.PropietarioXPoder = new ObservableListSource<PropietarioXPoder>();
            this.ExpedienteXPropietario = new ObservableListSource<ExpedienteXPropietario>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Documento { get; set; }
        public string RUC { get; set; }
        public string Personeria { get; set; }
        public string Obs { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int IdiomaID { get; set; }
        public Nullable<int> PaisID { get; set; }
        public Nullable<int> GrupoEmpresarialID { get; set; }
        public Nullable<int> CiudadID { get; set; }
    
        public virtual CIdioma CIdioma { get; set; }
        public virtual ObservableListSource<PropietarioXPoder> PropietarioXPoder { get; set; }
        public virtual ObservableListSource<ExpedienteXPropietario> ExpedienteXPropietario { get; set; }
        public virtual CPais CPais { get; set; }
    }
}
