//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_pagosolicitud
    {
        public ps_pagosolicitud()
        {
            this.mc_movimientoscuenta = new ObservableListSource<mc_movimientoscuenta>();
            this.sxp_solicitudesxpago = new ObservableListSource<sxp_solicitudesxpago>();
        }
    
        public int ps_pagosolicitudid { get; set; }
        public string ps_docorigen { get; set; }
        public Nullable<int> ps_proveedorid { get; set; }
        public string ps_proveedornrofactura { get; set; }
        public Nullable<System.DateTime> ps_proveedorfecfactura { get; set; }
        public int ps_monedaid { get; set; }
        public Nullable<int> ps_bancoid { get; set; }
        public Nullable<int> ps_cuentaid { get; set; }
        public int ps_formapagoid { get; set; }
        public System.DateTime ps_fechapago { get; set; }
        public string ps_nrocheque { get; set; }
        public Nullable<System.DateTime> ps_feccheque { get; set; }
        public Nullable<int> ps_bancochequeid { get; set; }
        public Nullable<int> ps_cuentachequeid { get; set; }
        public Nullable<int> ps_monedagastoid { get; set; }
        public Nullable<decimal> ps_gastocambiario { get; set; }
        public decimal ps_montopago { get; set; }
        public string ps_referencia { get; set; }
        public Nullable<System.DateTime> ps_fechaboletadeposito { get; set; }
        public string ps_nrorecibo { get; set; }
        public Nullable<System.DateTime> ps_fecharecibo { get; set; }
        public bool ps_anulado { get; set; }
        public Nullable<System.DateTime> ps_fechaanulacion { get; set; }
        public Nullable<System.DateTime> ps_fechanotacredito { get; set; }
        public string ps_notacreditonro { get; set; }
        public string ps_nombreproveedor { get; set; }
        public Nullable<int> ps_corresponsalid { get; set; }
        public string ps_nrotransaccion { get; set; }
        public string ps_codreferencia { get; set; }
    
        public virtual ba_banco ba_banco { get; set; }
        public virtual ba_banco ba_banco1 { get; set; }
        public virtual cb_cuentabanco cb_cuentabanco { get; set; }
        public virtual cb_cuentabanco cb_cuentabanco1 { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual fp_formadepago fp_formadepago { get; set; }
        public virtual ObservableListSource<mc_movimientoscuenta> mc_movimientoscuenta { get; set; }
        public virtual pr_proveedor pr_proveedor { get; set; }
        public virtual ps_pagosolicitud ps_pagosolicitud1 { get; set; }
        public virtual ps_pagosolicitud ps_pagosolicitud2 { get; set; }
        public virtual ObservableListSource<sxp_solicitudesxpago> sxp_solicitudesxpago { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
