//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ra_reporteasunto
    {
        public int ra_reporteasuntoid { get; set; }
        public string ra_reporte_id { get; set; }
        public string ra_asunto_esp { get; set; }
        public string ra_asunto_ing { get; set; }
    }
}
