//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class rc_reclamocliente
    {
        public rc_reclamocliente()
        {
            this.rd_reclamoclientedetalle = new ObservableListSource<rd_reclamoclientedetalle>();
        }
    
        public int rc_reclamoclienteid { get; set; }
        public System.DateTime rc_fechareclamo { get; set; }
        public int rc_usuarioid { get; set; }
        public string rc_textoreclamo { get; set; }
        public decimal rc_total { get; set; }
        public int rc_monedaid { get; set; }
        public int rc_clienteid { get; set; }
        public string rc_from { get; set; }
        public string rc_to { get; set; }
        public string rc_cc { get; set; }
        public string rc_bcc { get; set; }
        public string rc_subject { get; set; }
        public string rc_referencia { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ObservableListSource<rd_reclamoclientedetalle> rd_reclamoclientedetalle { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
