//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class rch_recibocheque
    {
        public int rch_recibochequeid { get; set; }
        public int rch_reciboid { get; set; }
        public System.DateTime rch_fechacheque { get; set; }
        public int rch_bancoid { get; set; }
        public string rch_numero { get; set; }
        public decimal rch_monto { get; set; }
    
        public virtual re_recibo re_recibo { get; set; }
        public virtual re_recibo re_recibo1 { get; set; }
    }
}
