//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class rcm_relacotizamone
    {
        public int ID { get; set; }
        public int MonedaID { get; set; }
        public decimal Factor { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Moneda Moneda1 { get; set; }
    }
}
