//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class re_recibo
    {
        public re_recibo()
        {
            this.pp_pagopresupuesto = new ObservableListSource<pp_pagopresupuesto>();
            this.rch_recibocheque = new ObservableListSource<rch_recibocheque>();
            this.rch_recibocheque1 = new ObservableListSource<rch_recibocheque>();
            this.rf_recibofactura = new ObservableListSource<rf_recibofactura>();
            this.rr_reciboretencion = new ObservableListSource<rr_reciboretencion>();
            this.rt_recibotransf = new ObservableListSource<rt_recibotransf>();
            this.dr_depositorecaudacion = new ObservableListSource<dr_depositorecaudacion>();
        }
    
        public int re_reciboid { get; set; }
        public System.DateTime re_fecha { get; set; }
        public string re_numero { get; set; }
        public int re_timbradoid { get; set; }
        public int re_clienteid { get; set; }
        public int re_monedaid { get; set; }
        public decimal re_totalrecibo { get; set; }
        public decimal re_totalnc { get; set; }
        public decimal re_montoret10 { get; set; }
        public decimal re_montoretrenta { get; set; }
        public decimal re_totaltransf { get; set; }
        public decimal re_totalgastos { get; set; }
        public decimal re_totalcheques { get; set; }
        public decimal re_totalefectivo { get; set; }
        public string re_concepto { get; set; }
        public Nullable<int> re_usuarioid { get; set; }
        public bool re_anulado { get; set; }
        public Nullable<System.DateTime> re_fechaanulacion { get; set; }
        public string re_usuarioanulacion { get; set; }
    
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto { get; set; }
        public virtual ObservableListSource<rch_recibocheque> rch_recibocheque { get; set; }
        public virtual ObservableListSource<rch_recibocheque> rch_recibocheque1 { get; set; }
        public virtual ObservableListSource<rf_recibofactura> rf_recibofactura { get; set; }
        public virtual ObservableListSource<rr_reciboretencion> rr_reciboretencion { get; set; }
        public virtual ObservableListSource<rt_recibotransf> rt_recibotransf { get; set; }
        public virtual ObservableListSource<dr_depositorecaudacion> dr_depositorecaudacion { get; set; }
        public virtual ti_timbrado ti_timbrado { get; set; }
    }
}
