//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    
    public partial class ReporteExportacionStarsoftSerie1
    {
        public string Fecha { get; set; }
        public string Ruc { get; set; }
        public string Cliente { get; set; }
        public string vendedor { get; set; }
        public string Zona { get; set; }
        public string Centro { get; set; }
        public string T_Comprobante { get; set; }
        public string Nro_Comprobante { get; set; }
        public string Forma_de_Pago { get; set; }
        public string Moneda { get; set; }
        public string Depósito { get; set; }
        public string Suc_ { get; set; }
        public Nullable<decimal> T_Cambio { get; set; }
        public Nullable<int> Total { get; set; }
        public string Producto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Cant_ { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> Grav__05 { get; set; }
        public Nullable<int> Grav__10 { get; set; }
        public Nullable<int> Exenta { get; set; }
        public Nullable<int> Iva_10 { get; set; }
        public Nullable<int> Iva_05 { get; set; }
        public Nullable<int> Comision { get; set; }
        public Nullable<int> Comision_Me { get; set; }
        public Nullable<long> Timbrado { get; set; }
        public Nullable<int> Tipo_NotaCredito { get; set; }
        public string Comentario { get; set; }
        public string Contribuyente { get; set; }
        public Nullable<int> Total_ME { get; set; }
        public Nullable<int> Precio_ME { get; set; }
        public Nullable<int> Descuento { get; set; }
        public Nullable<int> Descuento_ME { get; set; }
        public string CantCuota_s { get; set; }
        public string Vencecad_dias_ { get; set; }
    }
}
