//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    
    public partial class ReporteExportacionStarsoftSerie2
    {
        public string ven_tipimp { get; set; }
        public Nullable<int> ven_gra05 { get; set; }
        public Nullable<int> ven_iva05 { get; set; }
        public string ven_disg05 { get; set; }
        public string cta_iva05 { get; set; }
        public Nullable<int> ven_rubgra { get; set; }
        public Nullable<int> ven_rubg05 { get; set; }
        public string ven_disexe { get; set; }
        public string ven_numero { get; set; }
        public string ven_imputa { get; set; }
        public string ven_sucurs { get; set; }
        public string generar { get; set; }
        public string form_pag { get; set; }
        public string ven_centro { get; set; }
        public string ven_provee { get; set; }
        public string ven_cuenta { get; set; }
        public string ven_prvnom { get; set; }
        public string ven_tipofa { get; set; }
        public string ven_fecha { get; set; }
        public Nullable<int> ven_totfac { get; set; }
        public Nullable<int> ven_exenta { get; set; }
        public Nullable<int> ven_gravad { get; set; }
        public Nullable<int> ven_iva { get; set; }
        public Nullable<int> ven_retenc { get; set; }
        public Nullable<int> ven_aux { get; set; }
        public Nullable<int> ven_ctrl { get; set; }
        public string ven_con { get; set; }
        public Nullable<int> ven_cuota { get; set; }
        public string ven_fecven { get; set; }
        public Nullable<int> cant_dias { get; set; }
        public string origen { get; set; }
        public Nullable<decimal> cambio { get; set; }
        public decimal valor { get; set; }
        public string moneda { get; set; }
        public Nullable<int> exen_dolar { get; set; }
        public string concepto { get; set; }
        public string cta_iva { get; set; }
        public string cta_caja { get; set; }
        public Nullable<int> tkdesde { get; set; }
        public Nullable<int> tkhasta { get; set; }
        public Nullable<int> caja { get; set; }
        public string ven_disgra { get; set; }
        public string forma_devo { get; set; }
        public string ven_cuense { get; set; }
        public Nullable<int> anular { get; set; }
        public string reproceso { get; set; }
        public string cuenta_exe { get; set; }
        public string usu_ide { get; set; }
        public Nullable<long> rucvennrotim { get; set; }
        public Nullable<int> clieasi { get; set; }
        public string ventirptip { get; set; }
        public string ventirpgra { get; set; }
        public string ventimporteirp { get; set; }
        public string ventirpexe { get; set; }
        public string irpc { get; set; }
        public string ivasimplificado { get; set; }
        public string ven_gdc { get; set; }
        public string venrubrogdc { get; set; }
        public string ven_gdccosto { get; set; }
        public string ven_gdcventa { get; set; }
        public string ven_gdcori { get; set; }
        public string ven_nronc { get; set; }
        public string ven_nctim { get; set; }
        public string ventipcli { get; set; }
    }
}
