//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class rm_rolmenu
    {
        public int rm_rolmenuid { get; set; }
        public Nullable<int> rm_rolid { get; set; }
        public Nullable<int> rm_menuid { get; set; }
    
        public virtual ro_rol ro_rol { get; set; }
        public virtual mn_menu mn_menu { get; set; }
    }
}
