//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ro_rol
    {
        public ro_rol()
        {
            this.rm_rolmenu = new ObservableListSource<rm_rolmenu>();
            this.ru_rolusuario = new ObservableListSource<ru_rolusuario>();
        }
    
        public int ro_rolid { get; set; }
        public Nullable<int> ro_sistemaid { get; set; }
        public string ro_descripcion { get; set; }
        public Nullable<bool> ro_administrador { get; set; }
    
        public virtual ObservableListSource<rm_rolmenu> rm_rolmenu { get; set; }
        public virtual ObservableListSource<ru_rolusuario> ru_rolusuario { get; set; }
    }
}
