//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class rr_reciboretencion
    {
        public int rr_reciboretencionid { get; set; }
        public int rr_reciboid { get; set; }
        public int rr_facturaid { get; set; }
        public string rr_numero { get; set; }
        public System.DateTime rr_fecharetencion { get; set; }
        public decimal rr_montoretencioniva10 { get; set; }
        public decimal rr_montoretencionrenta { get; set; }
    
        public virtual fc_facturacabecera fc_facturacabecera { get; set; }
        public virtual re_recibo re_recibo { get; set; }
    }
}
