//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class rt_recibotransf
    {
        public int rt_recibotransfid { get; set; }
        public int rt_reciboid { get; set; }
        public System.DateTime rt_fechatransf { get; set; }
        public int rt_cuentabancoid { get; set; }
        public string rt_numero { get; set; }
        public decimal rt_montogasto { get; set; }
        public decimal rt_montotransf { get; set; }
    
        public virtual cb_cuentabanco cb_cuentabanco { get; set; }
        public virtual re_recibo re_recibo { get; set; }
    }
}
