//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ru_rolusuario
    {
        public int ru_rolusuarioid { get; set; }
        public Nullable<int> ru_rolid { get; set; }
        public Nullable<int> ru_usuarioid { get; set; }
        public Nullable<bool> ru_puedevertodo { get; set; }
    
        public virtual ro_rol ro_rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
