//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class sa_subarea
    {
        public int sa_subareaid { get; set; }
        public int sa_areaid { get; set; }
        public string sa_descripcion { get; set; }
    
        public virtual ac_areacontabilidad ac_areacontabilidad { get; set; }
    }
}
