//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class sec_solexclusioncab
    {
        public sec_solexclusioncab()
        {
            this.sed_solexclusiondet = new ObservableListSource<sed_solexclusiondet>();
        }
    
        public int sec_solexclusioncabid { get; set; }
        public int sec_proveedorid { get; set; }
        public string sec_nrofactura { get; set; }
        public System.DateTime sec_fechafactura { get; set; }
        public bool sec_activo { get; set; }
        public System.DateTime sec_fechaexclusion { get; set; }
        public decimal sec_importe { get; set; }
        public decimal sec_saldo { get; set; }
        public int sec_monedaid { get; set; }
        public Nullable<int> sec_tipofacturaid { get; set; }
    
        public virtual tf_tipofactura tf_tipofactura { get; set; }
        public virtual ObservableListSource<sed_solexclusiondet> sed_solexclusiondet { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
