//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class sed_solexclusiondet
    {
        public int sed_solexclusiondetid { get; set; }
        public int sed_solicitudpagodetid { get; set; }
        public int sed_solexclusioncabid { get; set; }
    
        public virtual sec_solexclusioncab sec_solexclusioncab { get; set; }
        public virtual spd_solicitudpagodet spd_solicitudpagodet { get; set; }
    }
}
