//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Situacion
    {
        public Situacion()
        {
            this.Tramite_Sit = new ObservableListSource<Tramite_Sit>();
            this.mu_mergeurgparte = new ObservableListSource<mu_mergeurgparte>();
        }
    
        public int ID { get; set; }
        public string Descrip { get; set; }
        public string Abrev { get; set; }
        public Nullable<bool> StandBy { get; set; }
        public Nullable<bool> EnTramite { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
    
        public virtual ObservableListSource<Tramite_Sit> Tramite_Sit { get; set; }
        public virtual ObservableListSource<mu_mergeurgparte> mu_mergeurgparte { get; set; }
    }
}
