//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class spac_solicitudpagoarchivocab
    {
        public spac_solicitudpagoarchivocab()
        {
            this.spad_solicitudpagoarchivodet = new ObservableListSource<spad_solicitudpagoarchivodet>();
        }
    
        public long spac_solicitudpagoarchivocabid { get; set; }
        public int spac_proveedorid { get; set; }
        public int spac_tipofacturaid { get; set; }
        public System.DateTime spac_fechafactura { get; set; }
        public string spac_nrofactura { get; set; }
        public decimal spac_montototal { get; set; }
        public bool spac_activo { get; set; }
    
        public virtual pr_proveedor pr_proveedor { get; set; }
        public virtual tf_tipofactura tf_tipofactura { get; set; }
        public virtual ObservableListSource<spad_solicitudpagoarchivodet> spad_solicitudpagoarchivodet { get; set; }
    }
}
