//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class spad_solicitudpagoarchivodet
    {
        public long spad_solicitudpagoarchivodetid { get; set; }
        public long spad_solicitudpagoarchivocabid { get; set; }
        public int spad_solicitudpagocabid { get; set; }
    
        public virtual spac_solicitudpagoarchivocab spac_solicitudpagoarchivocab { get; set; }
        public virtual spad_solicitudpagoarchivodet spad_solicitudpagoarchivodet1 { get; set; }
        public virtual spad_solicitudpagoarchivodet spad_solicitudpagoarchivodet2 { get; set; }
        public virtual spc_solicitudpagocab spc_solicitudpagocab { get; set; }
    }
}
