//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class spc_solicitudpagocab
    {
        public spc_solicitudpagocab()
        {
            this.sxp_solicitudesxpago = new ObservableListSource<sxp_solicitudesxpago>();
            this.spd_solicitudpagodet = new ObservableListSource<spd_solicitudpagodet>();
            this.spad_solicitudpagoarchivodet = new ObservableListSource<spad_solicitudpagoarchivodet>();
        }
    
        public int spc_solicitudpagocabid { get; set; }
        public Nullable<int> spc_expedienteid { get; set; }
        public Nullable<int> spc_ordentrabajoid { get; set; }
        public string spc_origen { get; set; }
        public bool spc_tiposolicitudpago { get; set; }
        public Nullable<int> spc_gastogeneralid { get; set; }
        public Nullable<int> spc_unidadnegocioid { get; set; }
        public int spc_monedaid { get; set; }
        public Nullable<int> spc_clienteid { get; set; }
        public Nullable<int> spc_tramiteid { get; set; }
        public Nullable<int> spc_actanro { get; set; }
        public Nullable<int> spc_actaanio { get; set; }
        public Nullable<int> spc_hinro { get; set; }
        public Nullable<int> spc_hianio { get; set; }
        public System.DateTime spc_fechasol { get; set; }
        public string spc_refcliente { get; set; }
        public string spc_observacion { get; set; }
        public decimal spc_importe { get; set; }
        public decimal spc_saldo { get; set; }
        public string spc_estado { get; set; }
        public Nullable<System.DateTime> spc_fechaanulacion { get; set; }
        public Nullable<int> spc_areaid { get; set; }
        public string spc_presupcabids { get; set; }
        public bool spc_tipoasociacionpresup { get; set; }
        public Nullable<bool> spc_excluirlistados { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual gg_gastogeneral gg_gastogeneral { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        public virtual spc_solicitudpagocab spc_solicitudpagocab1 { get; set; }
        public virtual spc_solicitudpagocab spc_solicitudpagocab2 { get; set; }
        public virtual un_unidadnegocio un_unidadnegocio { get; set; }
        public virtual ObservableListSource<sxp_solicitudesxpago> sxp_solicitudesxpago { get; set; }
        public virtual ObservableListSource<spd_solicitudpagodet> spd_solicitudpagodet { get; set; }
        public virtual ObservableListSource<spad_solicitudpagoarchivodet> spad_solicitudpagoarchivodet { get; set; }
        public virtual Tramite Tramite { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
