//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class su_serieusuario
    {
        public int su_serieusuarioid { get; set; }
        public int su_usuarioid { get; set; }
        public int su_timbradoid { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ti_timbrado ti_timbrado { get; set; }
    }
}
