//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class sxp_solicitudesxpago
    {
        public int sxp_solicitudxpagoid { get; set; }
        public int sxp_solicitudpagocabid { get; set; }
        public int sxp_pagosolicitudid { get; set; }
        public decimal sxp_monto { get; set; }
    
        public virtual sxp_solicitudesxpago sxp_solicitudesxpago1 { get; set; }
        public virtual sxp_solicitudesxpago sxp_solicitudesxpago2 { get; set; }
        public virtual spc_solicitudpagocab spc_solicitudpagocab { get; set; }
        public virtual ps_pagosolicitud ps_pagosolicitud { get; set; }
    }
}
