//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ta_tipoactuacion
    {
        public ta_tipoactuacion()
        {
            this.axe_actuacionxexpe = new ObservableListSource<axe_actuacionxexpe>();
        }
    
        public int ta_tipoactuacionid { get; set; }
        public string ta_descripcion { get; set; }
    
        public virtual ObservableListSource<axe_actuacionxexpe> axe_actuacionxexpe { get; set; }
    }
}
