//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ta_tipoantecedente
    {
        public ta_tipoantecedente()
        {
            this.ca_clienteantecedente = new ObservableListSource<ca_clienteantecedente>();
        }
    
        public int ta_tipoantecedenteid { get; set; }
        public string ta_descripantecedente { get; set; }
    
        public virtual ObservableListSource<ca_clienteantecedente> ca_clienteantecedente { get; set; }
    }
}
