//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarifas
    {
        public Tarifas()
        {
            this.tc_tarifascliente = new ObservableListSource<tc_tarifascliente>();
            this.trr_tramitetarifa = new ObservableListSource<trr_tramitetarifa>();
            this.Tarifas1 = new ObservableListSource<Tarifas>();
            this.spd_solicitudpagodet = new ObservableListSource<spd_solicitudpagodet>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionFactura { get; set; }
        public decimal Monto { get; set; }
        public int MonedaID { get; set; }
        public int TipoTarifaID { get; set; }
        public bool TipoUnidadDesc { get; set; }
        public decimal DescuentoMonto { get; set; }
        public decimal DescuentoPorcentaje { get; set; }
        public bool TipoUnidadImp { get; set; }
        public decimal ImpuestoMonto { get; set; }
        public decimal ImpuestoPorcentaje { get; set; }
        public decimal PrecioVenta { get; set; }
        public Nullable<decimal> TarifaExternaID { get; set; }
        public Nullable<decimal> ProveedorID { get; set; }
        public string Grupo { get; set; }
        public Nullable<int> TarifaGastoID { get; set; }
        public string Observacion { get; set; }
        public string DescripcionFacturaIngles { get; set; }
    
        public virtual tt_tipotarifa tt_tipotarifa { get; set; }
        public virtual ObservableListSource<tc_tarifascliente> tc_tarifascliente { get; set; }
        public virtual ObservableListSource<trr_tramitetarifa> trr_tramitetarifa { get; set; }
        public virtual ObservableListSource<Tarifas> Tarifas1 { get; set; }
        public virtual Tarifas Tarifas2 { get; set; }
        public virtual ObservableListSource<spd_solicitudpagodet> spd_solicitudpagodet { get; set; }
    }
}
