//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcd_tipocambiode
    {
        public int tcd_tipocambiodeid { get; set; }
        public System.DateTime tcd_fecha { get; set; }
        public int tcd_monedaid { get; set; }
        public decimal tcd_valor { get; set; }
    
        public virtual Moneda Moneda { get; set; }
    }
}
