//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_tipodocumento
    {
        public td_tipodocumento()
        {
            this.cnd_controlnumdoc = new ObservableListSource<cnd_controlnumdoc>();
            this.ad_autorizaciondocumento = new ObservableListSource<ad_autorizaciondocumento>();
            this.ti_timbrado = new ObservableListSource<ti_timbrado>();
        }
    
        public int td_tipodocumentoid { get; set; }
        public string td_descripcion { get; set; }
        public bool td_controlartimbrado { get; set; }
        public bool td_mostrar { get; set; }
        public int td_sistemaid { get; set; }
    
        public virtual ObservableListSource<cnd_controlnumdoc> cnd_controlnumdoc { get; set; }
        public virtual ObservableListSource<ad_autorizaciondocumento> ad_autorizaciondocumento { get; set; }
        public virtual ObservableListSource<ti_timbrado> ti_timbrado { get; set; }
    }
}
