//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class tf_tipofactura
    {
        public tf_tipofactura()
        {
            this.sec_solexclusioncab = new ObservableListSource<sec_solexclusioncab>();
            this.spd_solicitudpagodet = new ObservableListSource<spd_solicitudpagodet>();
            this.spac_solicitudpagoarchivocab = new ObservableListSource<spac_solicitudpagoarchivocab>();
        }
    
        public int tf_tipofacturaid { get; set; }
        public string tf_descripcion { get; set; }
        public string tf_abrev { get; set; }
    
        public virtual ObservableListSource<sec_solexclusioncab> sec_solexclusioncab { get; set; }
        public virtual ObservableListSource<spd_solicitudpagodet> spd_solicitudpagodet { get; set; }
        public virtual ObservableListSource<spac_solicitudpagoarchivocab> spac_solicitudpagoarchivocab { get; set; }
    }
}
