//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_tipomovimientocuenta
    {
        public tm_tipomovimientocuenta()
        {
            this.mc_movimientoscuenta = new ObservableListSource<mc_movimientoscuenta>();
        }
    
        public int tm_tipomovimientoid { get; set; }
        public string tm_tipomovimientodescrip { get; set; }
        public string tm_tipo { get; set; }
    
        public virtual ObservableListSource<mc_movimientoscuenta> mc_movimientoscuenta { get; set; }
    }
}
