//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajoTipo
    {
        public TrabajoTipo()
        {
            this.OrdenTrabajo = new ObservableListSource<OrdenTrabajo>();
            this.Tramite = new ObservableListSource<Tramite>();
        }
    
        public int ID { get; set; }
        public string Descrip { get; set; }
        public string Abrev { get; set; }
    
        public virtual ObservableListSource<OrdenTrabajo> OrdenTrabajo { get; set; }
        public virtual ObservableListSource<Tramite> Tramite { get; set; }
    }
}
