//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramite_Sit
    {
        public Tramite_Sit()
        {
            this.Expediente = new ObservableListSource<Expediente>();
            this.Merge_Expediente = new ObservableListSource<Merge_Expediente>();
        }
    
        public int ID { get; set; }
        public int TramiteID { get; set; }
        public int SituacionID { get; set; }
        public int Plazo { get; set; }
        public int UnidadID { get; set; }
        public bool Vigente { get; set; }
        public Nullable<bool> Automatico { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
    
        public virtual ObservableListSource<Expediente> Expediente { get; set; }
        public virtual Situacion Situacion { get; set; }
        public virtual ObservableListSource<Merge_Expediente> Merge_Expediente { get; set; }
        public virtual Tramite Tramite { get; set; }
    }
}
