//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramite
    {
        public Tramite()
        {
            this.ClienteXTramite = new ObservableListSource<ClienteXTramite>();
            this.DocumentoPlantilla = new ObservableListSource<DocumentoPlantilla>();
            this.Expediente = new ObservableListSource<Expediente>();
            this.pc_presupuestocab = new ObservableListSource<pc_presupuestocab>();
            this.pp_partepresupuesto = new ObservableListSource<pp_partepresupuesto>();
            this.spc_solicitudpagocab = new ObservableListSource<spc_solicitudpagocab>();
            this.tc_tarifascliente = new ObservableListSource<tc_tarifascliente>();
            this.Tramite_Sit = new ObservableListSource<Tramite_Sit>();
            this.trr_tramitetarifa = new ObservableListSource<trr_tramitetarifa>();
        }
    
        public int ID { get; set; }
        public int ProcesoID { get; set; }
        public string Descrip { get; set; }
        public string Abrev { get; set; }
        public Nullable<int> TrabajoTipoID { get; set; }
        public string BolAbrev { get; set; }
        public Nullable<int> AreaContabID { get; set; }
        public string AbrevParaContabilidad { get; set; }
        public string EtiquetaEsp { get; set; }
        public string EtiquetaIng { get; set; }
        public Nullable<decimal> TasaDinapi { get; set; }
        public Nullable<decimal> TasaDinapiJornales { get; set; }
        public string BolDescrip { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
    
        public virtual ac_areacontabilidad ac_areacontabilidad { get; set; }
        public virtual ObservableListSource<ClienteXTramite> ClienteXTramite { get; set; }
        public virtual ObservableListSource<DocumentoPlantilla> DocumentoPlantilla { get; set; }
        public virtual ObservableListSource<Expediente> Expediente { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab { get; set; }
        public virtual ObservableListSource<pp_partepresupuesto> pp_partepresupuesto { get; set; }
        public virtual ObservableListSource<spc_solicitudpagocab> spc_solicitudpagocab { get; set; }
        public virtual ObservableListSource<tc_tarifascliente> tc_tarifascliente { get; set; }
        public virtual TrabajoTipo TrabajoTipo { get; set; }
        public virtual ObservableListSource<Tramite_Sit> Tramite_Sit { get; set; }
        public virtual ObservableListSource<trr_tramitetarifa> trr_tramitetarifa { get; set; }
    }
}
