//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class trr_tramitetarifa
    {
        public int ttr_id { get; set; }
        public int ttr_tramiteid { get; set; }
        public int ttr_tarifaid { get; set; }
    
        public virtual Tarifas Tarifas { get; set; }
        public virtual Tramite Tramite { get; set; }
    }
}
