//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_tipotarifa
    {
        public tt_tipotarifa()
        {
            this.Tarifas = new ObservableListSource<Tarifas>();
        }
    
        public int tt_id { get; set; }
        public string tt_descrip { get; set; }
    
        public virtual ObservableListSource<Tarifas> Tarifas { get; set; }
    }
}
