//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class un_unidadnegocio
    {
        public un_unidadnegocio()
        {
            this.ac_areacontabilidad = new ObservableListSource<ac_areacontabilidad>();
            this.spc_solicitudpagocab = new ObservableListSource<spc_solicitudpagocab>();
        }
    
        public int un_unidadnegocioid { get; set; }
        public string un_descripcion { get; set; }
    
        public virtual ObservableListSource<ac_areacontabilidad> ac_areacontabilidad { get; set; }
        public virtual ObservableListSource<spc_solicitudpagocab> spc_solicitudpagocab { get; set; }
    }
}
