//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelEF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.ca_clienteantecedente = new ObservableListSource<ca_clienteantecedente>();
            this.ca_clienteantecedente1 = new ObservableListSource<ca_clienteantecedente>();
            this.Correspondencia = new ObservableListSource<Correspondencia>();
            this.op_oposicion = new ObservableListSource<op_oposicion>();
            this.su_serieusuario = new ObservableListSource<su_serieusuario>();
            this.ru_rolusuario = new ObservableListSource<ru_rolusuario>();
            this.rc_reclamocliente = new ObservableListSource<rc_reclamocliente>();
            this.pc_presupuestocab = new ObservableListSource<pc_presupuestocab>();
            this.pc_presupuestocab1 = new ObservableListSource<pc_presupuestocab>();
            this.pc_presupuestocab2 = new ObservableListSource<pc_presupuestocab>();
            this.spd_solicitudpagodet = new ObservableListSource<spd_solicitudpagodet>();
            this.ad_autorizaciondocumento = new ObservableListSource<ad_autorizaciondocumento>();
            this.ad_autorizaciondocumento1 = new ObservableListSource<ad_autorizaciondocumento>();
            this.pp_pagopresupuesto = new ObservableListSource<pp_pagopresupuesto>();
            this.ti_timbrado = new ObservableListSource<ti_timbrado>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Usuario1 { get; set; }
        public string Nick { get; set; }
        public string Email { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string NombrePila { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Congreso { get; set; }
        public string Iniciales { get; set; }
        public string PasswordEmail { get; set; }
        public string UsuarioDominio2 { get; set; }
    
        public virtual ObservableListSource<ca_clienteantecedente> ca_clienteantecedente { get; set; }
        public virtual ObservableListSource<ca_clienteantecedente> ca_clienteantecedente1 { get; set; }
        public virtual CArea CArea { get; set; }
        public virtual ObservableListSource<Correspondencia> Correspondencia { get; set; }
        public virtual ObservableListSource<op_oposicion> op_oposicion { get; set; }
        public virtual ObservableListSource<su_serieusuario> su_serieusuario { get; set; }
        public virtual ObservableListSource<ru_rolusuario> ru_rolusuario { get; set; }
        public virtual ObservableListSource<rc_reclamocliente> rc_reclamocliente { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab1 { get; set; }
        public virtual ObservableListSource<pc_presupuestocab> pc_presupuestocab2 { get; set; }
        public virtual ObservableListSource<spd_solicitudpagodet> spd_solicitudpagodet { get; set; }
        public virtual ObservableListSource<ad_autorizaciondocumento> ad_autorizaciondocumento { get; set; }
        public virtual ObservableListSource<ad_autorizaciondocumento> ad_autorizaciondocumento1 { get; set; }
        public virtual ObservableListSource<pp_pagopresupuesto> pp_pagopresupuesto { get; set; }
        public virtual ObservableListSource<ti_timbrado> ti_timbrado { get; set; }
    }
}
